# you can override this using by setting a system property, for example -Des.logger.level=DEBUG
es.logger.level: INFO
rootLogger: ${es.logger.level}, console, index_search_log_file
logger:
  # log action execution errors for easier debugging
  action: DEBUG
  # reduce the logging for aws, too much is logged under the default INFO
  com.amazonaws: WARN

appender:
  console:
    type: console
    layout:
      type: consolePattern
      conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"

  index_search_log_file:
    type: dailyRollingFile
    file: ${path.logs}/${cluster.name}_index_search.log
    datePattern: "'.'yyyy-MM-dd"
    layout:
      type: pattern
      converstionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"

